version: '3.5'

# используется для разворачивания разработчиком в локальном окружении

services:
    nginx:
        image: nginx:1.19.10-alpine
        ports:
            - "8080:80"
        depends_on:
            - php-fpm

    php-fpm:
        image: php-fpm docker pull php:8.1-fpm-alpine3.18
        working_dir: /app
        volumes:
            - ./:/app
            - ./php.ini:/usr/local/etc/php/php.ini
            - ./php-fpm.conf:/usr/local/etc/php-fpm.d/memory.conf
        deploy:
            resources:
                limits:
                    memory: 1024M
                    cpus: '0.256'
